services:
  wordpress:
    build:
      context: ./setup/wordpress
      dockerfile: Dockerfile
    ports:
      - 8888:80
    env_file:
      - ./setup/wordpress/wordpress.env
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
    networks:
      - azure-network
  db:
    image: mariadb:11.6.2
    env_file:
      - ./setup/wordpress/wordpress.env
    volumes:
      - db:/var/lib/mysql
    networks:
      - azure-network
  azure-blob:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    entrypoint: ["azurite", "--blobHost", "0.0.0.0", "--blobPort", "10000","-l", "data"]
    ports:
      - "10000:10000" # Blob service
    volumes:
      - ./azure-data:/opt/azurite/data
  azure-cli:
    image: mcr.microsoft.com/azure-cli
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    depends_on:
      - azure-blob
    networks:
      - azure-network
volumes:
  db:
  wordpress:
networks:
  azure-network:
    driver: bridge